# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Realtek network device drivers.
#

obj-$(CONFIG_8139CP) += 8139cp.o
obj-$(CONFIG_8139TOO) += 8139too.o
obj-$(CONFIG_ATP) += atp.o
r8169-objs += r8169_main.o r8169_firmware.o r8169_phy_config.o
obj-$(CONFIG_R8169) += r8169.o
obj-$(CONFIG_R8125) += r8125_vendor/
obj-$(CONFIG_R8126) += r8126_vendor/
obj-$(CONFIG_R8168) += r8168_vendor/
